### PR TITLE
Added the discussions page and a few updates

### PR DESCRIPTION
**Pull request by ShadMickelberry**

### CODE REVIEW

**Comment by OGProgrammer** [comment]
I've upgraded the code to use a meetup api package that looks alot like what you built. Anyway this code would need refactoring so best to just start from master again and add this new page again.

**Comment by ShadMickelberry** [comment]
Sounds good thanks. Probably isn't even a very useful page to have. Do you think having something to document the talks with the slides and notes would be more useful?

**Comment by OGProgrammer** [comment]
Yea that is a great idea, I need to start bringing a camera and tripod to record them for sure, at the very least including the slideshows. Anyway, if we were to add something like this to the website, it would be really nice to just keep all of the talks in one or multiple "markdown" files and include those in the project. If you don't know what markdown is check out the following link https://help.github.com/articles/markdown-basics/

There is a PHP library at https://github.com/michelf/php-markdown that looks good. It turns markdown files into HTML and you can just output that. 

Just include the project by copying the string from packagist https://packagist.org/packages/michelf/php-markdown

"michelf/php-markdown": "~1.5"

(this means any version above 1.5 but no higher than 1.9) https://getcomposer.org/doc/01-basic-usage.md#package-versions
Id put something like that above into the require part of the composer.json file and run "composer update" to pull the dep down into the vendor directory. The tutorials on how to use it should be pretty straight forward from there since we are using the autoloader.

**Comment by ShadMickelberry** [comment]
Sounds good. This package looks easy enough to use. Was thinking one way would be to use some sort of directory structure like:
-meetings
    --2015
        ---0102.md
        ---0203.md
        ---0304.md
        ---0405.md
        ---0507.md
    --2014
        ---0102.md
        ---0203.md
        ---0304.md
        ---0405.md
        ---0507.md

Where the markdown file date is the date of the meeting? That may allow for a decent albeit rudimentary organization to it?

That sound okay or do you have another idea. Or we could just break down and use something like Wordpress  for this section :)

**Comment by OGProgrammer** [comment]
Yea def wanna put all those markdown files in a directory

**Pull request closed without merging**
